# -*- coding: utf-8 -*-
"""RSOpendata_crawler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxozEm0J6VjS66v_4ofXfuyJc9tTTWnA
"""

import requests
import os
import zipfile
import time
import pandas as pd

# 有發現下載連結的URL很相近，所以針對這個做了爬蟲
# 缺點是這個爬蟲目前好像會跟原本的落後一些，因為OpenData可以下載到的資料

def real_estate_crawler(year, season):
  if year > 1000:
    # 計算民國年
    year -= 1911

  # 定義 year 跟 season (後來注意到下載連結只有season= 的後面有像，只是找不太出來連結在哪，以及是否可以對到預售屋)
  res = requests.get("https://plvr.land.moi.gov.tw//DownloadSeason?season="+str(year)+"S"+str(season)+"&type=zip&fileName=lvr_landcsv.zip")

  # 寫入對應的資料夾
  housefile = str(year)+str(season)+'.zip'
  open(housefile, 'wb').write(res.content)

  # 製造另外的資料夾以方便資料擷取，如果沒有既有的資料夾就會製造新的資料夾 (避免多次下載相同檔案的去重)
  folder = 'real_estate' + str(year) + str(season)
  if not os.path.isdir(folder):
    os.mkdir(folder)

  # 解壓縮到資料夾，並命名為上面 folder 名稱
  with zipfile.ZipFile(housefile, 'r') as zip_ref:
      zip_ref.extractall(folder)

  # set rest time
  time.sleep(10)

# 下方是再colab環境中如果直接想要找資料的位置
# root_folder = '/content'

##建立預售屋的爬蟲 (未建立，下載網站上有標示預售屋的部分但須要確認如何找到下載連結URL，看是否可以做一樣的事情)
# def presale_crawler(year,season):

# 呼叫資料

# 因為最時價登錄剛開始的只有前兩季，所以另外附上
# real_estate_crawler(101, 3)
# real_estate_crawler(101, 4)

# 爬取並下載指定年間的資料 (要寫115才會有今年2025的)
for year in range(103, 114):
  #第一季到第四季
  for season in range(1,5):
    #print 來看跑的進度
    print(year, season)
    real_estate_crawler(year, season)

#再跑前今年前兩季 (如果一併放到前面迴圈會因為讀不到 (114,3) 而迴圈錯誤)
real_estate_crawler(114, 1)
real_estate_crawler(114, 2)

# 修正版 (解決沒有讀到target就跳掉)，製作按照區域的統合版csv

# 尋找指定檔案 ，例如 a_lvr_land_a.csv (台北全部交易)。
# 上面的 a 可以改成其他縣市的代號
target_filename = "a_lvr_land_a.csv"

# Content 是對應到爬蟲時生成資料夾的位置，看一下左方檔案看是什麼修成有爬蟲資料夾的東西即可
root_folder = '/content'

cleaned_df = []

for folder_name in os.listdir(root_folder):
    folder_path = os.path.join(root_folder, folder_name)

    if os.path.isdir(folder_path):
        file_path = os.path.join(folder_path, target_filename)

        if os.path.exists(file_path):
            try:
                #delimiter?
                df = pd.read_csv(file_path, skiprows=[1], header=0, encoding='utf-8')  # 略過第二行與把第一行當作標題
                cleaned_df.append(df)
                print(f"✅ Collected the target file in：{file_path}")
            except Exception as e:
                print(f"⚠️ Failed to read：{file_path}，Error：{e}")
        else:
            print(f"⏩ Target file not found in：{file_path}")


#將所有讀到的資料整合成一個df，如果直接用cleaned_df會變成一串dataframe，清洗方面會有問題
if cleaned_df:
    final_df = pd.concat(cleaned_df, ignore_index=True)
    print("✅ Finished combining target data")
else:
    print("⚠️ There are no data to combine")

#初步清洗步驟，會再考慮


final_df = final_df.drop_duplicates()

# 將「鄉鎮市區」欄位名稱改為「行政區」
final_df.rename(columns={"鄉鎮市區": "admin_area"}, inplace=True)
final_df.rename(columns={"土地位置建物門牌": "address"}, inplace=True)


#移除只有土地與車位的交易，這次只有看房地/房地+車位
# final_df = final_df[~final_df["交易標的"].str.contains("土地|車位", na=False)]

# 處理掉有些年份走調的資料比 (資料中有出現過)


#移除空白格與這次分析不需要的欄位，備註多半為親友交易、價格不正常之交易
final_df = final_df.drop(columns=["非都市土地使用分區","都市土地使用分區","交易筆棟數","電梯","移轉編號","車位總價元","備註","非都市土地使用編定","車位移轉總面積(平方公尺)"], errors='ignore')


# 更改欄位顯示方式()
# 按照年月份進行排列
final_df = final_df.sort_values(by="交易年月日")

final_df['單價元平方公尺'] = final_df['單價元平方公尺'].astype(float)
final_df['單價元坪'] = final_df['單價元平方公尺'] * 3.30579

# 前面沒有注意到少了一步，讓迴圈跑出來變成一個list 的dataframe，導致格式走樣
print(f"cleaned_df is: {type(cleaned_df)}")

# 後來將資料在集合成dataframe
print(f"final_df is: {type(final_df)}")

print(final_df)

# 寫入 CSV 檔案並下載
from google.colab import files
df_download = pd.DataFrame(final_df)

#客製化下載名稱，顯示是地方的集大成 (Target filename 是否需要改名)
output_filename = 'agg_' + target_filename

#記得 encoding
df_download.to_csv(output_filename, index=False, encoding='utf-8-sig')

#送到Google Drive再自動下載處理好的 csv
files.download(output_filename)

print("已成功儲存：")

#下載後面需要的Reporting 包裝，介紹所有欄位的工具
!pip install ydata-profiling
!pip install wordcloud

#由於 matplotlib 或 seaborn 預設字型不支援中文，部分有改到，但文字雲有些自己的問題存在

import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']  # 或 ['SimHei']
plt.rcParams['axes.unicode_minus'] = False  # 避免負號顯示錯誤

# 測試 Pandas Profiling，畫面顯示
import pandas as pd
from ydata_profiling import ProfileReport

#針對清理好的 pandas dataframe 進行 Profiling (只接受 pandas)
profile = ProfileReport(final_df, title='Test Profile Report', explorative=True)
profile.to_notebook_iframe()

# 將report匯出 (可存到 html 或 json)
# profile.to_file('test_report.html')